apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile
spec:
  capacity:
    storage: 5Gi
  storageClassName: "azurefile"
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: crawlshare
    readOnly: false
  mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=0
  - gid=0
  - mfsymlinks
  - nobrl
  