apiVersion: v1
kind: Service
metadata:
  name: {{index .Values.service.crawlGitName }}
spec:
  selector:
    app: {{ .Values.service.crawlGitName }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{index .Values "service" "crawl-26-name" }}
# spec:
#   selector:
#     app: crawl-26
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080
