apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.crawlDeployment.name }}
  labels:
    {{- include "crawlapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.crawlDeployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.service.crawlGitName }}
      {{- include "crawlapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.crawlGitName }}
        {{- include "crawlapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.crawlDeployment.name }}
          image: "{{ .Values.crawlDeployment.repository }}:{{ .Values.crawlDeployment.tag }}"
          imagePullPolicy: {{ .Values.crawlDeployment.pullPolicy }}
          env:
            - name: URLBASE
              value: "http://crawl.kirbytoso.xyz:8080"
            - name: B2C_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: crawl-secrets
                  key: ckzcrawlAppId
            - name: B2C_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: crawl-secrets
                  key: ckzcrawlAppSecret
            - name: KV_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: crawl-secrets
                  key: kvClientId
            - name: KV_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: crawl-secrets
                  key: kvClientSecret
            - name: KV_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: crawl-secrets
                  key: kvTenantId
            - name: KV_NAME
              valueFrom:
                secretKeyRef:
                  name: crawl-secrets
                  key: kvName
          ports:
          - containerPort: {{ .Values.crawlDeployment.containerPort }}
          volumeMounts:
            {{- range $.Values.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .claimName }}
        {{- end }}
