apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.crawlDeployment.name }}
  labels:
    {{- include "crawlapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.crawlDeployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.service.crawlGitName }}
      {{- include "crawlapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.crawlGitName }}
        {{- include "crawlapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.crawlDeployment.name }}
          image: "{{ .Values.crawlDeployment.repository }}:{{ .Values.crawlDeployment.tag }}"
          imagePullPolicy: {{ .Values.crawlDeployment.pullPolicy }}
          ports:
          - containerPort: {{ .Values.crawlDeployment.containerPort }}
          volumeMounts:
            {{- range $.Values.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .claimName }}
        {{- end }}
