# This is a SecretProviderClass using an Azure service principal to access Keyvault
{{- if .Values.azureKeyvault }}
{{- with .Values.azureKeyvault }}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
  - secretName: ingress-tls-csi # how to insert this as block literal from values.yaml?
    type: kubernetes.io/tls
    data: 
    - objectName: dkcrawl
      key: tls.key
    - objectName: dkcrawl
      key: tls.crt
  parameters:
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    useVMManagedIdentity: "true"
    keyvaultName: {{ .name }}          # the name of the KeyVault
    userAssignedIdentityID: {{ .userAssignedIdentityID }}
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: dkcrawl
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    tenantId: {{ .tenantId }}                 # the tenant ID of the KeyVault
{{- end }}
{{- end }}