apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolumes.name }}
spec:
  capacity:
    storage: 5Gi
  storageClassName: {{ .Values.persistentVolumes.storageClassName }}
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: crawlshare
    readOnly: false
  mountOptions:
  - dir_mode=0755
  - file_mode=0755
  - uid=0
  - gid=0
  - mfsymlinks
  - nobrl