apiVersion: v1
kind: Service
metadata:
  name: {{index .Values.service.scoringName }}
spec:
  selector:
    app: {{ .Values.service.scoringName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80