apiVersion: v1
kind: Service
metadata:
  name: {{index .Values "service" "crawl-git-name" }}
spec:
  selector:
    app: crawl-git
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{index .Values "service" "crawl-26-name" }}
spec:
  selector:
    app: crawl-26
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{index .Values "service" "crawl-scoring-name" }}
spec:
  selector:
    app: scoring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80