# This is a SecretProviderClass example using a service principal to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvcrawl
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data: 
    - objectName: dkcrawl
      key: tls.key
    - objectName: dkcrawl
      key: tls.crt
  parameters:
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    useVMManagedIdentity: "true"
    keyvaultName: "kvcrawl"          # the name of the KeyVault
    userAssignedIdentityID: "9ea90dc3-0c82-4ced-b898-43cdce52edfb"
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: dkcrawl
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"                 # the tenant ID of the KeyVault