apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crawl-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.org/proxy-read-timeout: "3600s"
    nginx.org/proxy-send-timeout: "3600s"
  labels:
    aadpodidbinding: azure-pod-identity-binding-selector # The selector defined in AzureIdentityBinding in the previous step
spec:
  tls:
  - hosts:
    - crawl.kirbytoso.xyz
    secretName: csi-secrets-store-provider-azure-token-5xdc5
  rules:
  - http:
      paths:
      - path: /scoring
        pathType: Prefix
        backend:
          service:
            name: scoring-service
            port:
              number: 80
      - path: /morgue
        pathType: Prefix
        backend:
          service:
            name: scoring-service
            port:
              number: 80
      - path: /dcss-web-git
        pathType: Prefix
        backend:
          service:
            name: crawl-git-service
            port:
              number: 8080
      - path: /dcss-web-0.26
        pathType: Prefix
        backend:
          service:
            name: crawl-26-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crawl-git-service
            port:
              number: 8080