# Games are stored in order. The order of games you define in these files will
# be preserved, and the files will be loaded in sorted order.
# %n in paths and urls is replaced by the current username.
games:
    # Trunk games
    # - id: normal-web-trunk
    #   name: Play Crawl (development branch)
    #   crawl_binary: /crawl-git/bin/crawl
    #   rcfile_path: /data/rcs/git
    #   macro_path: /data/rcs/git
    #   morgue_path: /data/morgue/%n/
    #   socket_path: /websockets
    #   dir_path: /data/logfiles/git
    #   inprogress_path: /data/inprogress/git
    #   ttyrec_path: /data/ttyrecs/%n
    #   client_path: /webserver/game_data/
    #   morgue_url: None
    #   show_save_info: True
    #   send_json_options: True
    - id: tut-web-trunk
      name: Tutorial
      crawl_binary: /crawl-git/bin/crawl
      rcfile_path: /data/rcs/git
      macro_path: /data/rcs/git
      morgue_path: /data/morgue/%n/
      inprogress_path: /data/inprogress/git
      ttyrec_path: /data/ttyrecs/%n
      socket_path: /websockets
      client_path: /webserver/game_data/
      dir_path: /data/logfiles/git
      morgue_url: None
      show_save_info: True
      send_json_options: True
      options:
        - -tutorial
    - id: sprint-web-trunk
      name: Sprint
      crawl_binary: /crawl-git/bin/crawl
      rcfile_path: /data/rcs/git
      macro_path: /data/rcs/git
      morgue_path: /data/morgue/%n/
      inprogress_path: /data/inprogress/git
      ttyrec_path: /data/ttyrecs/%n
      socket_path: /websockets
      client_path: /webserver/game_data/
      dir_path: /data/logfiles/git
      morgue_url: None
      show_save_info: True
      send_json_options: True
      options:
        - -sprint