# Games are stored in order. The order of games you define in these files will
# be preserved, and the files will be loaded in sorted order.
# %n in paths and urls is replaced by the current username.
games:
    # Trunk games
    - id: normal-web-trunk
      name: Play Crawl (development branch)
      crawl_binary: /crawl-git/bin/crawl
      rcfile_path: /data/rcs/git
      macro_path: /data/rcs/git
      morgue_path: /data/morgue/%n/
      socket_path: /websockets
      dir_path: /data/logfiles/git
      inprogress_path: /data/inprogress/git
      ttyrec_path: /data/ttyrec/%n
      client_path: /crawl-git
      morgue_url: https://crawl.kirbytoso.xyz/morgue/%n/
      show_save_info: True
      send_json_options: True
    - id: tut-web-trunk
      name: Tutorial
      crawl_binary: /crawl-git/bin/crawl
      rcfile_path: /data/rcs/git
      macro_path: /data/rcs/git
      morgue_path: /data/morgue/%n/
      inprogress_path: /data/inprogress/git
      ttyrec_path: /data/ttyrec/%n
      socket_path: /websockets
      client_path: /crawl-git
      dir_path: /data/logfiles/git
      morgue_url: https://crawl.kirbytoso.xyz/morgue/%n/
      show_save_info: True
      send_json_options: True
      options:
        - -tutorial
    - id: sprint-web-trunk
      name: Sprint
      crawl_binary: /crawl-git/bin/crawl
      rcfile_path: /data/rcs/git
      macro_path: /data/rcs/git
      morgue_path: /data/morgue/%n/
      inprogress_path: /data/inprogress/git
      ttyrec_path: /data/ttyrec/%n
      socket_path: /websockets
      client_path: /crawl-git
      dir_path: /data/logfiles/git
      morgue_url: https://crawl.kirbytoso.xyz/morgue/%n/
      show_save_info: True
      send_json_options: True
      options:
        - -sprint
    # v27 games
    - id: normal-web-27
      name: Play Crawl (v27)
      crawl_binary: /crawl-27/bin/crawl
      rcfile_path: /data/rcs/27
      macro_path: /data/rcs/27
      morgue_path: /data/morgue/%n/
      socket_path: /websockets
      dir_path: /data/logfiles/27
      inprogress_path: /data/inprogress/27
      ttyrec_path: /data/ttyrec/%n
      client_path: /crawl-27
      morgue_url: https://crawl.kirbytoso.xyz/morgue/%n/
      show_save_info: True
      send_json_options: True
    - id: tut-web-27
      name: Tutorial
      crawl_binary: /crawl-27/bin/crawl
      rcfile_path: /data/rcs/27
      macro_path: /data/rcs/27
      morgue_path: /data/morgue/%n/
      inprogress_path: /data/inprogress/27
      ttyrec_path: /data/ttyrec/%n
      socket_path: /websockets
      client_path: /crawl-27
      dir_path: /data/logfiles/27
      morgue_url: https://crawl.kirbytoso.xyz/morgue/%n/
      show_save_info: True
      send_json_options: True
      options:
        - -tutorial
    - id: sprint-web-27
      name: Sprint
      crawl_binary: /crawl-27/bin/crawl
      rcfile_path: /data/rcs/27
      macro_path: /data/rcs/27
      morgue_path: /data/morgue/%n/
      inprogress_path: /data/inprogress/27
      ttyrec_path: /data/ttyrec/%n
      socket_path: /websockets
      client_path: /crawl-27
      dir_path: /data/logfiles/27
      morgue_url: https://crawl.kirbytoso.xyz/morgue/%n/
      show_save_info: True
      send_json_options: True
      options:
        - -sprint
    # v26 games
    - id: normal-web-26
      name: Play Crawl (v26)
      crawl_binary: /crawl-26/bin/crawl
      rcfile_path: /data/rcs/26
      macro_path: /data/rcs/26
      morgue_path: /data/morgue/%n/
      socket_path: /websockets
      dir_path: /data/logfiles/26
      inprogress_path: /data/inprogress/26
      ttyrec_path: /data/ttyrec/%n
      client_path: /crawl-26
      morgue_url: https://crawl.kirbytoso.xyz/morgue/%n/
      show_save_info: True
      send_json_options: True
    - id: tut-web-26
      name: Tutorial
      crawl_binary: /crawl-26/bin/crawl
      rcfile_path: /data/rcs/26
      macro_path: /data/rcs/26
      morgue_path: /data/morgue/%n/
      inprogress_path: /data/inprogress/26
      ttyrec_path: /data/ttyrec/%n
      socket_path: /websockets
      client_path: /crawl-26
      dir_path: /data/logfiles/26
      morgue_url: https://crawl.kirbytoso.xyz/morgue/%n/
      show_save_info: True
      send_json_options: True
      options:
        - -tutorial
    - id: sprint-web-26
      name: Sprint
      crawl_binary: /crawl-26/bin/crawl
      rcfile_path: /data/rcs/26
      macro_path: /data/rcs/26
      morgue_path: /data/morgue/%n/
      inprogress_path: /data/inprogress/26
      ttyrec_path: /data/ttyrec/%n
      socket_path: /websockets
      client_path: /crawl-26
      dir_path: /data/logfiles/26
      morgue_url: https://crawl.kirbytoso.xyz/morgue/%n/
      show_save_info: True
      send_json_options: True
      options:
        - -sprint