apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data: 
    - objectName: dkcrawl
      key: tls.key
    - objectName: dkcrawl
      key: tls.crt
  - secretName: azure-files-secret
    type: kubernetes.io/Opaque
    data:
    - objectName: azFilesName
      key: azurestorageaccountname
    - objectName: azFilesKey
      key: azurestorageaccountkey
  - secretName: crawl-secrets
    type: kubernetes.io/Opaque
    data:
    - objectName: kvName
      key: kvName
    - objectName: kvTenantId
      key: kvTenantId
    - objectName: kvClientId
      key: kvClientId
    - objectName: kvClientSecret
      key: kvClientSecret
    - objectName: ckzcrawlAppId
      key: ckzcrawlAppId
    - objectName: ckzcrawlAppSecret
      key: ckzcrawlAppSecret
    - objectName: ckzcrawlMainUserPassword
      key: ckzcrawlMainUserPassword
    - objectName: redisConnectionString
      key: redisConnectionString
  parameters:
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    useVMManagedIdentity: "true"
    keyvaultName: kvcrawl          # the name of the KeyVault
    userAssignedIdentityID: 6ff3171f-7df0-448c-bdcf-c1086ba13376 # 9ea90dc3-0c82-4ced-b898-43cdce52edfb
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - | 
          objectName: dkcrawl
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - | 
          objectName: azFilesName
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: azFilesKey
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: kvName
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: kvTenantId
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: kvClientSecret
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: kvClientId
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: ckzcrawlAppId
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: ckzcrawlAppSecret
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: ckzcrawlMainUserPassword
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: redisConnectionString
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47                 # the tenant ID of the KeyVault